services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        BRANCH_NAME: ${CI_COMMIT_REF_NAME}
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /certbot/www:/var/www/certbot/:ro
      - /etc/letsencrypt/:/etc/nginx/ssl/:ro
      - /var/log:/var/log
      - /var/www/tablecrm-app:/var/www/app
      - /var/www/tablecrm-landing:/var/www/landing
      - /photos:/nginx/photos
    networks:
      - nginx-proxy
      - infrastructure
      - shared_services
    depends_on:
      - adminer

  certbot:
    image: certbot/certbot:latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - /certbot/www/:/var/www/certbot/:rw
      - /etc/letsencrypt/:/etc/letsencrypt/:rw
    networks:
      - nginx-proxy

  db:
    image: postgres:14.2
    container_name: postgres_container
    restart: always
    command: postgres -c 'config_file=/etc/postgresql.conf'
    ports:
      - "48425:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf:ro
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: cash_2
    networks:
      - nginx-proxy
      - infrastructure

  backup:
    build: ./backup
    restart: always
    environment:
      SCHEDULE: '@hourly'
      BACKUP_KEEP_DAYS: 14
      S3_ENDPOINT: https://storage.clo.ru/
      S3_REGION: eu-north-1
      S3_ACCESS_KEY_ID: ${S3_BACKUPS_ACCESSKEY}
      S3_SECRET_ACCESS_KEY: ${S3_BACKUPS_SECRETKEY}
      S3_BUCKET: apps3tablecrm-default-bucket
      S3_PREFIX: backups/mastertablecrm
      POSTGRES_HOST: db
      POSTGRES_DATABASE: cash_2
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      PGDUMP_EXTRA_OPTS: '--exclude-table-data=events'
    networks:
      - nginx-proxy

  adminer:
    image: adminer
    restart: always
    networks:
      - nginx-proxy
    depends_on:
      - db

  backend:
    build: ./backend
    image: tablecrm_backend:latest
    restart: always
    command: bash -c "alembic upgrade head && uvicorn main:app --host=0.0.0.0 --port 8000 --log-level=info"
    volumes:
      - ./backend:/backend
      - /certs:/certs
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      APPLE_PASS_TYPE_ID: ${APPLE_PASS_TYPE_ID}
      APPLE_TEAM_ID: ${APPLE_TEAM_ID}
      APPLE_CERTIFICATE_PATH: ${APPLE_CERTIFICATE_PATH}
      APPLE_KEY_PATH: ${APPLE_KEY_PATH}
      APPLE_WWDR_PATH: ${APPLE_WWDR_PATH}
      APPLE_NOTIFICATION_PATH: ${APPLE_NOTIFICATION_PATH}
      APPLE_NOTIFICATION_KEY: ${APPLE_NOTIFICATION_KEY}
      PKPASS_PASSWORD: ${PKPASS_PASSWORD}
      APP_URL: ${APP_URL}
      S3_ACCESS: ${S3_ACCESS}
      S3_SECRET: ${S3_SECRET}
      S3_URL: ${S3_URL}
      TG_TOKEN: ${TG_TOKEN}
      CHEQUES_TOKEN: ${CHEQUES_TOKEN}
      ACCOUNT_INTERVAL: ${ACCOUNT_INTERVAL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      XDG_RUNTIME_DIR: ./tmp
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      GEOAPIFY_SECRET: ${GEOAPIFY_SECRET}
    networks:
      - nginx-proxy
      - infrastructure

  worker:
    image: tablecrm_backend:latest
    restart: always
    command: bash -c "python3 worker.py"
    volumes:
      - ./backend:/backend
      - /certs:/certs
    environment:
      APPLE_PASS_TYPE_ID: ${APPLE_PASS_TYPE_ID}
      APPLE_TEAM_ID: ${APPLE_TEAM_ID}
      APPLE_CERTIFICATE_PATH: ${APPLE_CERTIFICATE_PATH}
      APPLE_KEY_PATH: ${APPLE_KEY_PATH}
      APPLE_WWDR_PATH: ${APPLE_WWDR_PATH}
      APPLE_NOTIFICATION_PATH: ${APPLE_NOTIFICATION_PATH}
      APPLE_NOTIFICATION_KEY: ${APPLE_NOTIFICATION_KEY}
      PKPASS_PASSWORD: ${PKPASS_PASSWORD}
      APP_URL: ${APP_URL}
      S3_ACCESS: ${S3_ACCESS}
      S3_SECRET: ${S3_SECRET}
      S3_URL: ${S3_URL}
      TG_TOKEN: ${TG_TOKEN}
      CHEQUES_TOKEN: ${CHEQUES_TOKEN}
      ACCOUNT_INTERVAL: ${ACCOUNT_INTERVAL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      XDG_RUNTIME_DIR: ./tmp
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
    networks:
      - nginx-proxy
      - infrastructure

  backend_jobs:
    image: tablecrm_backend:latest
    restart: always
    command: bash -c "python3 start_jobs.py"
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    environment:
      APPLE_PASS_TYPE_ID: ${APPLE_PASS_TYPE_ID}
      APPLE_TEAM_ID: ${APPLE_TEAM_ID}
      APPLE_CERTIFICATE_PATH: ${APPLE_CERTIFICATE_PATH}
      APPLE_KEY_PATH: ${APPLE_KEY_PATH}
      APPLE_WWDR_PATH: ${APPLE_WWDR_PATH}
      APPLE_NOTIFICATION_PATH: ${APPLE_NOTIFICATION_PATH}
      APPLE_NOTIFICATION_KEY: ${APPLE_NOTIFICATION_KEY}
      PKPASS_PASSWORD: ${PKPASS_PASSWORD}
      APP_URL: ${APP_URL}
      S3_ACCESS: ${S3_ACCESS}
      S3_SECRET: ${S3_SECRET}
      S3_URL: ${S3_URL}
      TG_TOKEN: ${TG_TOKEN}
      CHEQUES_TOKEN: ${CHEQUES_TOKEN}
      ACCOUNT_INTERVAL: ${ACCOUNT_INTERVAL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      XDG_RUNTIME_DIR: ./tmp
    networks:
      - nginx-proxy

  teleg_bot:
    image: tablecrm_backend:latest
    restart: always
    command: python3 bot.py
    volumes:
      - ./backend:/backend
      - /photos:/backend/photos
    depends_on:
      - backend
    environment:
      APP_URL: ${APP_URL}
      TG_TOKEN: ${TG_TOKEN}
      CHEQUES_TOKEN: ${CHEQUES_TOKEN}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_PORT: ${POSTGRES_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      S3_ACCESS: ${S3_ACCESS}
      S3_SECRET: ${S3_SECRET}
      S3_URL: ${S3_URL}
    networks:
      - nginx-proxy
      - infrastructure

  message_consumer_task:
    build: ./backend
    restart: always
    command: python3 message_consumer.py
    volumes:
      - ./backend:/backend
    environment:
      APPLE_PASS_TYPE_ID: ${APPLE_PASS_TYPE_ID}
      APPLE_TEAM_ID: ${APPLE_TEAM_ID}
      APPLE_CERTIFICATE_PATH: ${APPLE_CERTIFICATE_PATH}
      APPLE_KEY_PATH: ${APPLE_KEY_PATH}
      APPLE_WWDR_PATH: ${APPLE_WWDR_PATH}
      APPLE_NOTIFICATION_PATH: ${APPLE_NOTIFICATION_PATH}
      APPLE_NOTIFICATION_KEY: ${APPLE_NOTIFICATION_KEY}
      PKPASS_PASSWORD: ${PKPASS_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      TG_TOKEN: ${TG_TOKEN}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      S3_ACCESS: ${S3_ACCESS}
      S3_SECRET: ${S3_SECRET}
      S3_URL: ${S3_URL}
    networks:
      - nginx-proxy
      - infrastructure

volumes:
  pgdata:

networks:
  nginx-proxy:
    name: tablecrm_nginx-proxy
    external: true
  infrastructure:
    name: infrastructure
    external: true
  shared_services:
    external: true
