global:
  scrape_interval:     15s
  evaluation_interval: 15s


scrape_configs:

  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["prometheus:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: "rabbitmq"
    static_configs:
    - targets: ["rabbitmq:15692"]

  - job_name: telegraf
    metrics_path: /metrics
    static_configs:
    - targets: ["telegraf:9126"]

  - job_name: "nginx-json-exporter"
    static_configs:
      - targets: ["194.87.215.9:8005"]
    scrape_interval: 15s